# Generated by Django 5.1.3 on 2024-11-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewandrating',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
