# Generated by Django 5.1.3 on 2024-12-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_reviewandrating_table_alter_vehicle_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image_urls',
            new_name='image_data',
        ),
    ]
