# Generated by Django 5.1.3 on 2024-12-11 09:21

import django.core.validators
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_image_urls_vehicle_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='daily_rent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_data',
            field=models.JSONField(default=vehicles.models.default_vehicle_image),
        ),
    ]
