# Generated by Django 5.1.3 on 2024-11-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
